name: vasp-first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello vasp-GHA"
      - name: Print goodbye
        run: echo "Goodbye vasp-GHA"
        

      
